version: 0.1

phases:
  install:
    commands:
      - 'echo "Install jscs..."'
      - 'npm install -g jscs'
  pre_build:
    commands:
      - 'echo "AWS CodeBuild src directory is ${CODEBUILD_SRC_DIR}"'
      - 'npm install'
  build:
    commands:
      - 'echo "Run jscs..."'
      - 'gulp jscs'
      - 'echo "Package as ZIP file"'
      - 'zip -r "suitec-preview-service_${CODEBUILD_BUILD_ID}.zip" * -x logs\*'
  post_build:
    commands:
      - 'echo "Artifact is ready for deployment: ${ARTIFACT_NAME}"'

artifacts:
  files:
    - suitec-preview-service_${CODEBUILD_BUILD_ID}.zip
  discard-paths: yes
