version: 0.1

phases:
  install:
    commands:
      - 'echo "Install jscs..."'
      - 'npm install -g jscs'
  pre_build:
    commands:
      - 'echo "AWS CodeBuild src directory is ${CODEBUILD_SRC_DIR}"'
      - 'npm install'
  build:
    commands:
      - 'echo "Run jscs..."'
      - './node_modules/.bin/gulp jscs'
      - 'echo "Package as ZIP file"'
      - 'zip -r "suitec-preview-service.zip" * -x logs\*'
  post_build:
    commands:
      - 'echo "Artifact is ready for deployment"'

artifacts:
  files:
    - suitec-preview-service.zip
  discard-paths: yes
