version: 0.1

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::234923831700:role/service-role/code-build-suitec-preview-service-service-role
  ComputeType: Linux
  Image: aws/codebuild/nodejs:6.3.1
  Timeout: 60

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - ./node_modules/.bin/gulp jscs
  build:
    commands:
      - echo "build phase"
  post_build:
    commands:
      - rm -Rf node_modules

artifacts:
  files:
    - '.ebextensions/*'
    - '.elasticbeanstalk/*'
    - '.gitignore'
    - '**/*'
