version: 0.1

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::234923831700:role/service-role/code-build-suitec-preview-service-service-role
  ComputeType: Linux
  Image: aws/codebuild/nodejs:6.3.1
  Timeout: 60

phases:
  install:
    commands:
      - echo "NPM installs..."
      - npm install --save-dev gulp
      - npm install --save-dev gulp-jscs
      - npm install --save-dev jscs
  pre_build:
    commands:
      - echo "CodeBuild src directory is ${CODEBUILD_SRC_DIR}"
  build:
    commands:
      - echo "Run jscs..."
      - cd "${CODEBUILD_SRC_DIR}"
      - ./node_modules/.bin/gulp jscs
  post_build:
    commands:
      - echo "The 'build' phase is done"

artifacts:
  files:
    - '.ebextensions/**/*'
    - '.elasticbeanstalk/**/*'
    - '**/*'
